CREATE DATABASE checkout;

USE checkout;

CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(40) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE userShip (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  street1 VARCHAR(255) NOT NULL,
  street2 VARCHAR(255),
  city VARCHAR(255) NOT NULL,
  state VARCHAR(2) NOT NULL,
  zip INT NOT NULL,
  phone INT NOT NULL,

  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE cc (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  number INT NOT NULL,
  cvv INT NOT NULL,
  zip INT NOT NULL,

  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
